# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b46a6bb4cbced9e9925b2c40e3fadc0f76bf34837028eb84f453423d1077eecd4d6f0907cef5d8dd772665de297ddb638fecad4314d066d793b18d6541234377

test:
  secret_key_base: fc11d96ed54556d980791be04246119aa2d3ef0bb37dca92200ca53a432527aa1daeed7510440791ffb1b9126448c39a1b15bf167329cefc05cd4078e33513ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
